// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: coresdk/v1/flags.proto
// Protobuf Java Version: 4.34.1

package coresdk.v1;

@com.google.protobuf.Generated
public final class Flags extends com.google.protobuf.GeneratedFile {
  private Flags() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "Flags");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EvaluateFlagRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:coresdk.v1.EvaluateFlagRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string flag_key = 1 [json_name = "flagKey"];</code>
     * @return The flagKey.
     */
    java.lang.String getFlagKey();
    /**
     * <code>string flag_key = 1 [json_name = "flagKey"];</code>
     * @return The bytes for flagKey.
     */
    com.google.protobuf.ByteString
        getFlagKeyBytes();

    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return The tenantId.
     */
    java.lang.String getTenantId();
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return The bytes for tenantId.
     */
    com.google.protobuf.ByteString
        getTenantIdBytes();

    /**
     * <code>string user_id = 3 [json_name = "userId"];</code>
     * @return The userId.
     */
    java.lang.String getUserId();
    /**
     * <code>string user_id = 3 [json_name = "userId"];</code>
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>string attributes_json = 4 [json_name = "attributesJson"];</code>
     * @return The attributesJson.
     */
    java.lang.String getAttributesJson();
    /**
     * <code>string attributes_json = 4 [json_name = "attributesJson"];</code>
     * @return The bytes for attributesJson.
     */
    com.google.protobuf.ByteString
        getAttributesJsonBytes();
  }
  /**
   * Protobuf type {@code coresdk.v1.EvaluateFlagRequest}
   */
  public static final class EvaluateFlagRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:coresdk.v1.EvaluateFlagRequest)
      EvaluateFlagRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 1,
        /* suffix= */ "",
        "EvaluateFlagRequest");
    }
    // Use EvaluateFlagRequest.newBuilder() to construct.
    private EvaluateFlagRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private EvaluateFlagRequest() {
      flagKey_ = "";
      tenantId_ = "";
      userId_ = "";
      attributesJson_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return coresdk.v1.Flags.internal_static_coresdk_v1_EvaluateFlagRequest_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return coresdk.v1.Flags.internal_static_coresdk_v1_EvaluateFlagRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return coresdk.v1.Flags.internal_static_coresdk_v1_EvaluateFlagRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              coresdk.v1.Flags.EvaluateFlagRequest.class, coresdk.v1.Flags.EvaluateFlagRequest.Builder.class);
    }

    public static final int FLAG_KEY_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object flagKey_ = "";
    /**
     * <code>string flag_key = 1 [json_name = "flagKey"];</code>
     * @return The flagKey.
     */
    @java.lang.Override
    public java.lang.String getFlagKey() {
      java.lang.Object ref = flagKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        flagKey_ = s;
        return s;
      }
    }
    /**
     * <code>string flag_key = 1 [json_name = "flagKey"];</code>
     * @return The bytes for flagKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFlagKeyBytes() {
      java.lang.Object ref = flagKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        flagKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TENANT_ID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object tenantId_ = "";
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return The tenantId.
     */
    @java.lang.Override
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      }
    }
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return The bytes for tenantId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_ID_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object userId_ = "";
    /**
     * <code>string user_id = 3 [json_name = "userId"];</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string user_id = 3 [json_name = "userId"];</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ATTRIBUTES_JSON_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object attributesJson_ = "";
    /**
     * <code>string attributes_json = 4 [json_name = "attributesJson"];</code>
     * @return The attributesJson.
     */
    @java.lang.Override
    public java.lang.String getAttributesJson() {
      java.lang.Object ref = attributesJson_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        attributesJson_ = s;
        return s;
      }
    }
    /**
     * <code>string attributes_json = 4 [json_name = "attributesJson"];</code>
     * @return The bytes for attributesJson.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAttributesJsonBytes() {
      java.lang.Object ref = attributesJson_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        attributesJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(flagKey_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, flagKey_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, tenantId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, userId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(attributesJson_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, attributesJson_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(flagKey_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, flagKey_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, tenantId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, userId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(attributesJson_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, attributesJson_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof coresdk.v1.Flags.EvaluateFlagRequest)) {
        return super.equals(obj);
      }
      coresdk.v1.Flags.EvaluateFlagRequest other = (coresdk.v1.Flags.EvaluateFlagRequest) obj;

      if (!getFlagKey()
          .equals(other.getFlagKey())) return false;
      if (!getTenantId()
          .equals(other.getTenantId())) return false;
      if (!getUserId()
          .equals(other.getUserId())) return false;
      if (!getAttributesJson()
          .equals(other.getAttributesJson())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FLAG_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getFlagKey().hashCode();
      hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTenantId().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + ATTRIBUTES_JSON_FIELD_NUMBER;
      hash = (53 * hash) + getAttributesJson().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static coresdk.v1.Flags.EvaluateFlagRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coresdk.v1.Flags.EvaluateFlagRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coresdk.v1.Flags.EvaluateFlagRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coresdk.v1.Flags.EvaluateFlagRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coresdk.v1.Flags.EvaluateFlagRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coresdk.v1.Flags.EvaluateFlagRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coresdk.v1.Flags.EvaluateFlagRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static coresdk.v1.Flags.EvaluateFlagRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static coresdk.v1.Flags.EvaluateFlagRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static coresdk.v1.Flags.EvaluateFlagRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static coresdk.v1.Flags.EvaluateFlagRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static coresdk.v1.Flags.EvaluateFlagRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(coresdk.v1.Flags.EvaluateFlagRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code coresdk.v1.EvaluateFlagRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:coresdk.v1.EvaluateFlagRequest)
        coresdk.v1.Flags.EvaluateFlagRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return coresdk.v1.Flags.internal_static_coresdk_v1_EvaluateFlagRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return coresdk.v1.Flags.internal_static_coresdk_v1_EvaluateFlagRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                coresdk.v1.Flags.EvaluateFlagRequest.class, coresdk.v1.Flags.EvaluateFlagRequest.Builder.class);
      }

      // Construct using coresdk.v1.Flags.EvaluateFlagRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        flagKey_ = "";
        tenantId_ = "";
        userId_ = "";
        attributesJson_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return coresdk.v1.Flags.internal_static_coresdk_v1_EvaluateFlagRequest_descriptor;
      }

      @java.lang.Override
      public coresdk.v1.Flags.EvaluateFlagRequest getDefaultInstanceForType() {
        return coresdk.v1.Flags.EvaluateFlagRequest.getDefaultInstance();
      }

      @java.lang.Override
      public coresdk.v1.Flags.EvaluateFlagRequest build() {
        coresdk.v1.Flags.EvaluateFlagRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public coresdk.v1.Flags.EvaluateFlagRequest buildPartial() {
        coresdk.v1.Flags.EvaluateFlagRequest result = new coresdk.v1.Flags.EvaluateFlagRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(coresdk.v1.Flags.EvaluateFlagRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.flagKey_ = flagKey_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.tenantId_ = tenantId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.attributesJson_ = attributesJson_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof coresdk.v1.Flags.EvaluateFlagRequest) {
          return mergeFrom((coresdk.v1.Flags.EvaluateFlagRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(coresdk.v1.Flags.EvaluateFlagRequest other) {
        if (other == coresdk.v1.Flags.EvaluateFlagRequest.getDefaultInstance()) return this;
        if (!other.getFlagKey().isEmpty()) {
          flagKey_ = other.flagKey_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getTenantId().isEmpty()) {
          tenantId_ = other.tenantId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getAttributesJson().isEmpty()) {
          attributesJson_ = other.attributesJson_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                flagKey_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                tenantId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                userId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                attributesJson_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object flagKey_ = "";
      /**
       * <code>string flag_key = 1 [json_name = "flagKey"];</code>
       * @return The flagKey.
       */
      public java.lang.String getFlagKey() {
        java.lang.Object ref = flagKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          flagKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string flag_key = 1 [json_name = "flagKey"];</code>
       * @return The bytes for flagKey.
       */
      public com.google.protobuf.ByteString
          getFlagKeyBytes() {
        java.lang.Object ref = flagKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          flagKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string flag_key = 1 [json_name = "flagKey"];</code>
       * @param value The flagKey to set.
       * @return This builder for chaining.
       */
      public Builder setFlagKey(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        flagKey_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string flag_key = 1 [json_name = "flagKey"];</code>
       * @return This builder for chaining.
       */
      public Builder clearFlagKey() {
        flagKey_ = getDefaultInstance().getFlagKey();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string flag_key = 1 [json_name = "flagKey"];</code>
       * @param value The bytes for flagKey to set.
       * @return This builder for chaining.
       */
      public Builder setFlagKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        flagKey_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object tenantId_ = "";
      /**
       * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
       * @return The tenantId.
       */
      public java.lang.String getTenantId() {
        java.lang.Object ref = tenantId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tenantId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
       * @return The bytes for tenantId.
       */
      public com.google.protobuf.ByteString
          getTenantIdBytes() {
        java.lang.Object ref = tenantId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tenantId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
       * @param value The tenantId to set.
       * @return This builder for chaining.
       */
      public Builder setTenantId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        tenantId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearTenantId() {
        tenantId_ = getDefaultInstance().getTenantId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
       * @param value The bytes for tenantId to set.
       * @return This builder for chaining.
       */
      public Builder setTenantIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        tenantId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>string user_id = 3 [json_name = "userId"];</code>
       * @return The userId.
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_id = 3 [json_name = "userId"];</code>
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_id = 3 [json_name = "userId"];</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        userId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 3 [json_name = "userId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        userId_ = getDefaultInstance().getUserId();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 3 [json_name = "userId"];</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        userId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object attributesJson_ = "";
      /**
       * <code>string attributes_json = 4 [json_name = "attributesJson"];</code>
       * @return The attributesJson.
       */
      public java.lang.String getAttributesJson() {
        java.lang.Object ref = attributesJson_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          attributesJson_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string attributes_json = 4 [json_name = "attributesJson"];</code>
       * @return The bytes for attributesJson.
       */
      public com.google.protobuf.ByteString
          getAttributesJsonBytes() {
        java.lang.Object ref = attributesJson_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          attributesJson_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string attributes_json = 4 [json_name = "attributesJson"];</code>
       * @param value The attributesJson to set.
       * @return This builder for chaining.
       */
      public Builder setAttributesJson(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        attributesJson_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string attributes_json = 4 [json_name = "attributesJson"];</code>
       * @return This builder for chaining.
       */
      public Builder clearAttributesJson() {
        attributesJson_ = getDefaultInstance().getAttributesJson();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string attributes_json = 4 [json_name = "attributesJson"];</code>
       * @param value The bytes for attributesJson to set.
       * @return This builder for chaining.
       */
      public Builder setAttributesJsonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        attributesJson_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:coresdk.v1.EvaluateFlagRequest)
    }

    // @@protoc_insertion_point(class_scope:coresdk.v1.EvaluateFlagRequest)
    private static final coresdk.v1.Flags.EvaluateFlagRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new coresdk.v1.Flags.EvaluateFlagRequest();
    }

    public static coresdk.v1.Flags.EvaluateFlagRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EvaluateFlagRequest>
        PARSER = new com.google.protobuf.AbstractParser<EvaluateFlagRequest>() {
      @java.lang.Override
      public EvaluateFlagRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EvaluateFlagRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EvaluateFlagRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public coresdk.v1.Flags.EvaluateFlagRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EvaluateFlagResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:coresdk.v1.EvaluateFlagResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool enabled = 1 [json_name = "enabled"];</code>
     * @return The enabled.
     */
    boolean getEnabled();

    /**
     * <code>string variant = 2 [json_name = "variant"];</code>
     * @return The variant.
     */
    java.lang.String getVariant();
    /**
     * <code>string variant = 2 [json_name = "variant"];</code>
     * @return The bytes for variant.
     */
    com.google.protobuf.ByteString
        getVariantBytes();

    /**
     * <code>string reason = 3 [json_name = "reason"];</code>
     * @return The reason.
     */
    java.lang.String getReason();
    /**
     * <code>string reason = 3 [json_name = "reason"];</code>
     * @return The bytes for reason.
     */
    com.google.protobuf.ByteString
        getReasonBytes();

    /**
     * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
     * @return Whether the error field is set.
     */
    boolean hasError();
    /**
     * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
     * @return The error.
     */
    coresdk.v1.Common.ProblemDetail getError();
    /**
     * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
     */
    coresdk.v1.Common.ProblemDetailOrBuilder getErrorOrBuilder();
  }
  /**
   * Protobuf type {@code coresdk.v1.EvaluateFlagResponse}
   */
  public static final class EvaluateFlagResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:coresdk.v1.EvaluateFlagResponse)
      EvaluateFlagResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 1,
        /* suffix= */ "",
        "EvaluateFlagResponse");
    }
    // Use EvaluateFlagResponse.newBuilder() to construct.
    private EvaluateFlagResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private EvaluateFlagResponse() {
      variant_ = "";
      reason_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return coresdk.v1.Flags.internal_static_coresdk_v1_EvaluateFlagResponse_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return coresdk.v1.Flags.internal_static_coresdk_v1_EvaluateFlagResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return coresdk.v1.Flags.internal_static_coresdk_v1_EvaluateFlagResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              coresdk.v1.Flags.EvaluateFlagResponse.class, coresdk.v1.Flags.EvaluateFlagResponse.Builder.class);
    }

    private int bitField0_;
    public static final int ENABLED_FIELD_NUMBER = 1;
    private boolean enabled_ = false;
    /**
     * <code>bool enabled = 1 [json_name = "enabled"];</code>
     * @return The enabled.
     */
    @java.lang.Override
    public boolean getEnabled() {
      return enabled_;
    }

    public static final int VARIANT_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object variant_ = "";
    /**
     * <code>string variant = 2 [json_name = "variant"];</code>
     * @return The variant.
     */
    @java.lang.Override
    public java.lang.String getVariant() {
      java.lang.Object ref = variant_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        variant_ = s;
        return s;
      }
    }
    /**
     * <code>string variant = 2 [json_name = "variant"];</code>
     * @return The bytes for variant.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVariantBytes() {
      java.lang.Object ref = variant_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        variant_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REASON_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object reason_ = "";
    /**
     * <code>string reason = 3 [json_name = "reason"];</code>
     * @return The reason.
     */
    @java.lang.Override
    public java.lang.String getReason() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reason_ = s;
        return s;
      }
    }
    /**
     * <code>string reason = 3 [json_name = "reason"];</code>
     * @return The bytes for reason.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReasonBytes() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERROR_FIELD_NUMBER = 4;
    private coresdk.v1.Common.ProblemDetail error_;
    /**
     * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
     * @return Whether the error field is set.
     */
    @java.lang.Override
    public boolean hasError() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
     * @return The error.
     */
    @java.lang.Override
    public coresdk.v1.Common.ProblemDetail getError() {
      return error_ == null ? coresdk.v1.Common.ProblemDetail.getDefaultInstance() : error_;
    }
    /**
     * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
     */
    @java.lang.Override
    public coresdk.v1.Common.ProblemDetailOrBuilder getErrorOrBuilder() {
      return error_ == null ? coresdk.v1.Common.ProblemDetail.getDefaultInstance() : error_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (enabled_ != false) {
        output.writeBool(1, enabled_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(variant_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, variant_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(reason_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, reason_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(4, getError());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (enabled_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, enabled_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(variant_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, variant_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(reason_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, reason_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getError());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof coresdk.v1.Flags.EvaluateFlagResponse)) {
        return super.equals(obj);
      }
      coresdk.v1.Flags.EvaluateFlagResponse other = (coresdk.v1.Flags.EvaluateFlagResponse) obj;

      if (getEnabled()
          != other.getEnabled()) return false;
      if (!getVariant()
          .equals(other.getVariant())) return false;
      if (!getReason()
          .equals(other.getReason())) return false;
      if (hasError() != other.hasError()) return false;
      if (hasError()) {
        if (!getError()
            .equals(other.getError())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ENABLED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getEnabled());
      hash = (37 * hash) + VARIANT_FIELD_NUMBER;
      hash = (53 * hash) + getVariant().hashCode();
      hash = (37 * hash) + REASON_FIELD_NUMBER;
      hash = (53 * hash) + getReason().hashCode();
      if (hasError()) {
        hash = (37 * hash) + ERROR_FIELD_NUMBER;
        hash = (53 * hash) + getError().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static coresdk.v1.Flags.EvaluateFlagResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coresdk.v1.Flags.EvaluateFlagResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coresdk.v1.Flags.EvaluateFlagResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coresdk.v1.Flags.EvaluateFlagResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coresdk.v1.Flags.EvaluateFlagResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coresdk.v1.Flags.EvaluateFlagResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coresdk.v1.Flags.EvaluateFlagResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static coresdk.v1.Flags.EvaluateFlagResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static coresdk.v1.Flags.EvaluateFlagResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static coresdk.v1.Flags.EvaluateFlagResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static coresdk.v1.Flags.EvaluateFlagResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static coresdk.v1.Flags.EvaluateFlagResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(coresdk.v1.Flags.EvaluateFlagResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code coresdk.v1.EvaluateFlagResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:coresdk.v1.EvaluateFlagResponse)
        coresdk.v1.Flags.EvaluateFlagResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return coresdk.v1.Flags.internal_static_coresdk_v1_EvaluateFlagResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return coresdk.v1.Flags.internal_static_coresdk_v1_EvaluateFlagResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                coresdk.v1.Flags.EvaluateFlagResponse.class, coresdk.v1.Flags.EvaluateFlagResponse.Builder.class);
      }

      // Construct using coresdk.v1.Flags.EvaluateFlagResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetErrorFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        enabled_ = false;
        variant_ = "";
        reason_ = "";
        error_ = null;
        if (errorBuilder_ != null) {
          errorBuilder_.dispose();
          errorBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return coresdk.v1.Flags.internal_static_coresdk_v1_EvaluateFlagResponse_descriptor;
      }

      @java.lang.Override
      public coresdk.v1.Flags.EvaluateFlagResponse getDefaultInstanceForType() {
        return coresdk.v1.Flags.EvaluateFlagResponse.getDefaultInstance();
      }

      @java.lang.Override
      public coresdk.v1.Flags.EvaluateFlagResponse build() {
        coresdk.v1.Flags.EvaluateFlagResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public coresdk.v1.Flags.EvaluateFlagResponse buildPartial() {
        coresdk.v1.Flags.EvaluateFlagResponse result = new coresdk.v1.Flags.EvaluateFlagResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(coresdk.v1.Flags.EvaluateFlagResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.enabled_ = enabled_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.variant_ = variant_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.reason_ = reason_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.error_ = errorBuilder_ == null
              ? error_
              : errorBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof coresdk.v1.Flags.EvaluateFlagResponse) {
          return mergeFrom((coresdk.v1.Flags.EvaluateFlagResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(coresdk.v1.Flags.EvaluateFlagResponse other) {
        if (other == coresdk.v1.Flags.EvaluateFlagResponse.getDefaultInstance()) return this;
        if (other.getEnabled() != false) {
          setEnabled(other.getEnabled());
        }
        if (!other.getVariant().isEmpty()) {
          variant_ = other.variant_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getReason().isEmpty()) {
          reason_ = other.reason_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasError()) {
          mergeError(other.getError());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                enabled_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                variant_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                reason_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    internalGetErrorFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean enabled_ ;
      /**
       * <code>bool enabled = 1 [json_name = "enabled"];</code>
       * @return The enabled.
       */
      @java.lang.Override
      public boolean getEnabled() {
        return enabled_;
      }
      /**
       * <code>bool enabled = 1 [json_name = "enabled"];</code>
       * @param value The enabled to set.
       * @return This builder for chaining.
       */
      public Builder setEnabled(boolean value) {

        enabled_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bool enabled = 1 [json_name = "enabled"];</code>
       * @return This builder for chaining.
       */
      public Builder clearEnabled() {
        bitField0_ = (bitField0_ & ~0x00000001);
        enabled_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object variant_ = "";
      /**
       * <code>string variant = 2 [json_name = "variant"];</code>
       * @return The variant.
       */
      public java.lang.String getVariant() {
        java.lang.Object ref = variant_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          variant_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string variant = 2 [json_name = "variant"];</code>
       * @return The bytes for variant.
       */
      public com.google.protobuf.ByteString
          getVariantBytes() {
        java.lang.Object ref = variant_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          variant_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string variant = 2 [json_name = "variant"];</code>
       * @param value The variant to set.
       * @return This builder for chaining.
       */
      public Builder setVariant(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        variant_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string variant = 2 [json_name = "variant"];</code>
       * @return This builder for chaining.
       */
      public Builder clearVariant() {
        variant_ = getDefaultInstance().getVariant();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string variant = 2 [json_name = "variant"];</code>
       * @param value The bytes for variant to set.
       * @return This builder for chaining.
       */
      public Builder setVariantBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        variant_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object reason_ = "";
      /**
       * <code>string reason = 3 [json_name = "reason"];</code>
       * @return The reason.
       */
      public java.lang.String getReason() {
        java.lang.Object ref = reason_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reason_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reason = 3 [json_name = "reason"];</code>
       * @return The bytes for reason.
       */
      public com.google.protobuf.ByteString
          getReasonBytes() {
        java.lang.Object ref = reason_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reason_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reason = 3 [json_name = "reason"];</code>
       * @param value The reason to set.
       * @return This builder for chaining.
       */
      public Builder setReason(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        reason_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string reason = 3 [json_name = "reason"];</code>
       * @return This builder for chaining.
       */
      public Builder clearReason() {
        reason_ = getDefaultInstance().getReason();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string reason = 3 [json_name = "reason"];</code>
       * @param value The bytes for reason to set.
       * @return This builder for chaining.
       */
      public Builder setReasonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        reason_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private coresdk.v1.Common.ProblemDetail error_;
      private com.google.protobuf.SingleFieldBuilder<
          coresdk.v1.Common.ProblemDetail, coresdk.v1.Common.ProblemDetail.Builder, coresdk.v1.Common.ProblemDetailOrBuilder> errorBuilder_;
      /**
       * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
       * @return Whether the error field is set.
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
       * @return The error.
       */
      public coresdk.v1.Common.ProblemDetail getError() {
        if (errorBuilder_ == null) {
          return error_ == null ? coresdk.v1.Common.ProblemDetail.getDefaultInstance() : error_;
        } else {
          return errorBuilder_.getMessage();
        }
      }
      /**
       * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
       */
      public Builder setError(coresdk.v1.Common.ProblemDetail value) {
        if (errorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          error_ = value;
        } else {
          errorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
       */
      public Builder setError(
          coresdk.v1.Common.ProblemDetail.Builder builderForValue) {
        if (errorBuilder_ == null) {
          error_ = builderForValue.build();
        } else {
          errorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
       */
      public Builder mergeError(coresdk.v1.Common.ProblemDetail value) {
        if (errorBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            error_ != null &&
            error_ != coresdk.v1.Common.ProblemDetail.getDefaultInstance()) {
            getErrorBuilder().mergeFrom(value);
          } else {
            error_ = value;
          }
        } else {
          errorBuilder_.mergeFrom(value);
        }
        if (error_ != null) {
          bitField0_ |= 0x00000008;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
       */
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000008);
        error_ = null;
        if (errorBuilder_ != null) {
          errorBuilder_.dispose();
          errorBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
       */
      public coresdk.v1.Common.ProblemDetail.Builder getErrorBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return internalGetErrorFieldBuilder().getBuilder();
      }
      /**
       * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
       */
      public coresdk.v1.Common.ProblemDetailOrBuilder getErrorOrBuilder() {
        if (errorBuilder_ != null) {
          return errorBuilder_.getMessageOrBuilder();
        } else {
          return error_ == null ?
              coresdk.v1.Common.ProblemDetail.getDefaultInstance() : error_;
        }
      }
      /**
       * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          coresdk.v1.Common.ProblemDetail, coresdk.v1.Common.ProblemDetail.Builder, coresdk.v1.Common.ProblemDetailOrBuilder> 
          internalGetErrorFieldBuilder() {
        if (errorBuilder_ == null) {
          errorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              coresdk.v1.Common.ProblemDetail, coresdk.v1.Common.ProblemDetail.Builder, coresdk.v1.Common.ProblemDetailOrBuilder>(
                  getError(),
                  getParentForChildren(),
                  isClean());
          error_ = null;
        }
        return errorBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:coresdk.v1.EvaluateFlagResponse)
    }

    // @@protoc_insertion_point(class_scope:coresdk.v1.EvaluateFlagResponse)
    private static final coresdk.v1.Flags.EvaluateFlagResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new coresdk.v1.Flags.EvaluateFlagResponse();
    }

    public static coresdk.v1.Flags.EvaluateFlagResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EvaluateFlagResponse>
        PARSER = new com.google.protobuf.AbstractParser<EvaluateFlagResponse>() {
      @java.lang.Override
      public EvaluateFlagResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EvaluateFlagResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EvaluateFlagResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public coresdk.v1.Flags.EvaluateFlagResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coresdk_v1_EvaluateFlagRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_coresdk_v1_EvaluateFlagRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coresdk_v1_EvaluateFlagResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_coresdk_v1_EvaluateFlagResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026coresdk/v1/flags.proto\022\ncoresdk.v1\032\027co" +
      "resdk/v1/common.proto\"\217\001\n\023EvaluateFlagRe" +
      "quest\022\031\n\010flag_key\030\001 \001(\tR\007flagKey\022\033\n\ttena" +
      "nt_id\030\002 \001(\tR\010tenantId\022\027\n\007user_id\030\003 \001(\tR\006" +
      "userId\022\'\n\017attributes_json\030\004 \001(\tR\016attribu" +
      "tesJson\"\223\001\n\024EvaluateFlagResponse\022\030\n\007enab" +
      "led\030\001 \001(\010R\007enabled\022\030\n\007variant\030\002 \001(\tR\007var" +
      "iant\022\026\n\006reason\030\003 \001(\tR\006reason\022/\n\005error\030\004 " +
      "\001(\0132\031.coresdk.v1.ProblemDetailR\005error2`\n" +
      "\013FlagService\022Q\n\014EvaluateFlag\022\037.coresdk.v" +
      "1.EvaluateFlagRequest\032 .coresdk.v1.Evalu" +
      "ateFlagResponseB.Z,github.com/coresdk-de" +
      "v/sdk-go/gen/coresdk/v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          coresdk.v1.Common.getDescriptor(),
        });
    internal_static_coresdk_v1_EvaluateFlagRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_coresdk_v1_EvaluateFlagRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_coresdk_v1_EvaluateFlagRequest_descriptor,
        new java.lang.String[] { "FlagKey", "TenantId", "UserId", "AttributesJson", });
    internal_static_coresdk_v1_EvaluateFlagResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_coresdk_v1_EvaluateFlagResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_coresdk_v1_EvaluateFlagResponse_descriptor,
        new java.lang.String[] { "Enabled", "Variant", "Reason", "Error", });
    descriptor.resolveAllFeaturesImmutable();
    coresdk.v1.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
