// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: coresdk/v1/license.proto
// Protobuf Java Version: 4.34.1

package coresdk.v1;

@com.google.protobuf.Generated
public final class License extends com.google.protobuf.GeneratedFile {
  private License() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "License");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CheckEntitlementRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:coresdk.v1.CheckEntitlementRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string entitlement_key = 1 [json_name = "entitlementKey"];</code>
     * @return The entitlementKey.
     */
    java.lang.String getEntitlementKey();
    /**
     * <code>string entitlement_key = 1 [json_name = "entitlementKey"];</code>
     * @return The bytes for entitlementKey.
     */
    com.google.protobuf.ByteString
        getEntitlementKeyBytes();

    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return The tenantId.
     */
    java.lang.String getTenantId();
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return The bytes for tenantId.
     */
    com.google.protobuf.ByteString
        getTenantIdBytes();
  }
  /**
   * Protobuf type {@code coresdk.v1.CheckEntitlementRequest}
   */
  public static final class CheckEntitlementRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:coresdk.v1.CheckEntitlementRequest)
      CheckEntitlementRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 1,
        /* suffix= */ "",
        "CheckEntitlementRequest");
    }
    // Use CheckEntitlementRequest.newBuilder() to construct.
    private CheckEntitlementRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CheckEntitlementRequest() {
      entitlementKey_ = "";
      tenantId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return coresdk.v1.License.internal_static_coresdk_v1_CheckEntitlementRequest_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return coresdk.v1.License.internal_static_coresdk_v1_CheckEntitlementRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return coresdk.v1.License.internal_static_coresdk_v1_CheckEntitlementRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              coresdk.v1.License.CheckEntitlementRequest.class, coresdk.v1.License.CheckEntitlementRequest.Builder.class);
    }

    public static final int ENTITLEMENT_KEY_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object entitlementKey_ = "";
    /**
     * <code>string entitlement_key = 1 [json_name = "entitlementKey"];</code>
     * @return The entitlementKey.
     */
    @java.lang.Override
    public java.lang.String getEntitlementKey() {
      java.lang.Object ref = entitlementKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        entitlementKey_ = s;
        return s;
      }
    }
    /**
     * <code>string entitlement_key = 1 [json_name = "entitlementKey"];</code>
     * @return The bytes for entitlementKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEntitlementKeyBytes() {
      java.lang.Object ref = entitlementKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entitlementKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TENANT_ID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object tenantId_ = "";
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return The tenantId.
     */
    @java.lang.Override
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      }
    }
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return The bytes for tenantId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(entitlementKey_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, entitlementKey_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, tenantId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(entitlementKey_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, entitlementKey_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, tenantId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof coresdk.v1.License.CheckEntitlementRequest)) {
        return super.equals(obj);
      }
      coresdk.v1.License.CheckEntitlementRequest other = (coresdk.v1.License.CheckEntitlementRequest) obj;

      if (!getEntitlementKey()
          .equals(other.getEntitlementKey())) return false;
      if (!getTenantId()
          .equals(other.getTenantId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ENTITLEMENT_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getEntitlementKey().hashCode();
      hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTenantId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static coresdk.v1.License.CheckEntitlementRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coresdk.v1.License.CheckEntitlementRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coresdk.v1.License.CheckEntitlementRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coresdk.v1.License.CheckEntitlementRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coresdk.v1.License.CheckEntitlementRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coresdk.v1.License.CheckEntitlementRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coresdk.v1.License.CheckEntitlementRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static coresdk.v1.License.CheckEntitlementRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static coresdk.v1.License.CheckEntitlementRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static coresdk.v1.License.CheckEntitlementRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static coresdk.v1.License.CheckEntitlementRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static coresdk.v1.License.CheckEntitlementRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(coresdk.v1.License.CheckEntitlementRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code coresdk.v1.CheckEntitlementRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:coresdk.v1.CheckEntitlementRequest)
        coresdk.v1.License.CheckEntitlementRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return coresdk.v1.License.internal_static_coresdk_v1_CheckEntitlementRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return coresdk.v1.License.internal_static_coresdk_v1_CheckEntitlementRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                coresdk.v1.License.CheckEntitlementRequest.class, coresdk.v1.License.CheckEntitlementRequest.Builder.class);
      }

      // Construct using coresdk.v1.License.CheckEntitlementRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        entitlementKey_ = "";
        tenantId_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return coresdk.v1.License.internal_static_coresdk_v1_CheckEntitlementRequest_descriptor;
      }

      @java.lang.Override
      public coresdk.v1.License.CheckEntitlementRequest getDefaultInstanceForType() {
        return coresdk.v1.License.CheckEntitlementRequest.getDefaultInstance();
      }

      @java.lang.Override
      public coresdk.v1.License.CheckEntitlementRequest build() {
        coresdk.v1.License.CheckEntitlementRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public coresdk.v1.License.CheckEntitlementRequest buildPartial() {
        coresdk.v1.License.CheckEntitlementRequest result = new coresdk.v1.License.CheckEntitlementRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(coresdk.v1.License.CheckEntitlementRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.entitlementKey_ = entitlementKey_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.tenantId_ = tenantId_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof coresdk.v1.License.CheckEntitlementRequest) {
          return mergeFrom((coresdk.v1.License.CheckEntitlementRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(coresdk.v1.License.CheckEntitlementRequest other) {
        if (other == coresdk.v1.License.CheckEntitlementRequest.getDefaultInstance()) return this;
        if (!other.getEntitlementKey().isEmpty()) {
          entitlementKey_ = other.entitlementKey_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getTenantId().isEmpty()) {
          tenantId_ = other.tenantId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                entitlementKey_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                tenantId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object entitlementKey_ = "";
      /**
       * <code>string entitlement_key = 1 [json_name = "entitlementKey"];</code>
       * @return The entitlementKey.
       */
      public java.lang.String getEntitlementKey() {
        java.lang.Object ref = entitlementKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          entitlementKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string entitlement_key = 1 [json_name = "entitlementKey"];</code>
       * @return The bytes for entitlementKey.
       */
      public com.google.protobuf.ByteString
          getEntitlementKeyBytes() {
        java.lang.Object ref = entitlementKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          entitlementKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string entitlement_key = 1 [json_name = "entitlementKey"];</code>
       * @param value The entitlementKey to set.
       * @return This builder for chaining.
       */
      public Builder setEntitlementKey(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        entitlementKey_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string entitlement_key = 1 [json_name = "entitlementKey"];</code>
       * @return This builder for chaining.
       */
      public Builder clearEntitlementKey() {
        entitlementKey_ = getDefaultInstance().getEntitlementKey();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string entitlement_key = 1 [json_name = "entitlementKey"];</code>
       * @param value The bytes for entitlementKey to set.
       * @return This builder for chaining.
       */
      public Builder setEntitlementKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        entitlementKey_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object tenantId_ = "";
      /**
       * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
       * @return The tenantId.
       */
      public java.lang.String getTenantId() {
        java.lang.Object ref = tenantId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tenantId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
       * @return The bytes for tenantId.
       */
      public com.google.protobuf.ByteString
          getTenantIdBytes() {
        java.lang.Object ref = tenantId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tenantId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
       * @param value The tenantId to set.
       * @return This builder for chaining.
       */
      public Builder setTenantId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        tenantId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearTenantId() {
        tenantId_ = getDefaultInstance().getTenantId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
       * @param value The bytes for tenantId to set.
       * @return This builder for chaining.
       */
      public Builder setTenantIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        tenantId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:coresdk.v1.CheckEntitlementRequest)
    }

    // @@protoc_insertion_point(class_scope:coresdk.v1.CheckEntitlementRequest)
    private static final coresdk.v1.License.CheckEntitlementRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new coresdk.v1.License.CheckEntitlementRequest();
    }

    public static coresdk.v1.License.CheckEntitlementRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CheckEntitlementRequest>
        PARSER = new com.google.protobuf.AbstractParser<CheckEntitlementRequest>() {
      @java.lang.Override
      public CheckEntitlementRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CheckEntitlementRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CheckEntitlementRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public coresdk.v1.License.CheckEntitlementRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CheckEntitlementResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:coresdk.v1.CheckEntitlementResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool entitled = 1 [json_name = "entitled"];</code>
     * @return The entitled.
     */
    boolean getEntitled();

    /**
     * <code>int64 numeric_value = 2 [json_name = "numericValue"];</code>
     * @return The numericValue.
     */
    long getNumericValue();

    /**
     * <code>int64 expires_at = 3 [json_name = "expiresAt"];</code>
     * @return The expiresAt.
     */
    long getExpiresAt();

    /**
     * <code>string plan = 4 [json_name = "plan"];</code>
     * @return The plan.
     */
    java.lang.String getPlan();
    /**
     * <code>string plan = 4 [json_name = "plan"];</code>
     * @return The bytes for plan.
     */
    com.google.protobuf.ByteString
        getPlanBytes();

    /**
     * <code>.coresdk.v1.ProblemDetail error = 5 [json_name = "error"];</code>
     * @return Whether the error field is set.
     */
    boolean hasError();
    /**
     * <code>.coresdk.v1.ProblemDetail error = 5 [json_name = "error"];</code>
     * @return The error.
     */
    coresdk.v1.Common.ProblemDetail getError();
    /**
     * <code>.coresdk.v1.ProblemDetail error = 5 [json_name = "error"];</code>
     */
    coresdk.v1.Common.ProblemDetailOrBuilder getErrorOrBuilder();
  }
  /**
   * Protobuf type {@code coresdk.v1.CheckEntitlementResponse}
   */
  public static final class CheckEntitlementResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:coresdk.v1.CheckEntitlementResponse)
      CheckEntitlementResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 1,
        /* suffix= */ "",
        "CheckEntitlementResponse");
    }
    // Use CheckEntitlementResponse.newBuilder() to construct.
    private CheckEntitlementResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CheckEntitlementResponse() {
      plan_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return coresdk.v1.License.internal_static_coresdk_v1_CheckEntitlementResponse_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return coresdk.v1.License.internal_static_coresdk_v1_CheckEntitlementResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return coresdk.v1.License.internal_static_coresdk_v1_CheckEntitlementResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              coresdk.v1.License.CheckEntitlementResponse.class, coresdk.v1.License.CheckEntitlementResponse.Builder.class);
    }

    private int bitField0_;
    public static final int ENTITLED_FIELD_NUMBER = 1;
    private boolean entitled_ = false;
    /**
     * <code>bool entitled = 1 [json_name = "entitled"];</code>
     * @return The entitled.
     */
    @java.lang.Override
    public boolean getEntitled() {
      return entitled_;
    }

    public static final int NUMERIC_VALUE_FIELD_NUMBER = 2;
    private long numericValue_ = 0L;
    /**
     * <code>int64 numeric_value = 2 [json_name = "numericValue"];</code>
     * @return The numericValue.
     */
    @java.lang.Override
    public long getNumericValue() {
      return numericValue_;
    }

    public static final int EXPIRES_AT_FIELD_NUMBER = 3;
    private long expiresAt_ = 0L;
    /**
     * <code>int64 expires_at = 3 [json_name = "expiresAt"];</code>
     * @return The expiresAt.
     */
    @java.lang.Override
    public long getExpiresAt() {
      return expiresAt_;
    }

    public static final int PLAN_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object plan_ = "";
    /**
     * <code>string plan = 4 [json_name = "plan"];</code>
     * @return The plan.
     */
    @java.lang.Override
    public java.lang.String getPlan() {
      java.lang.Object ref = plan_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        plan_ = s;
        return s;
      }
    }
    /**
     * <code>string plan = 4 [json_name = "plan"];</code>
     * @return The bytes for plan.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPlanBytes() {
      java.lang.Object ref = plan_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        plan_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERROR_FIELD_NUMBER = 5;
    private coresdk.v1.Common.ProblemDetail error_;
    /**
     * <code>.coresdk.v1.ProblemDetail error = 5 [json_name = "error"];</code>
     * @return Whether the error field is set.
     */
    @java.lang.Override
    public boolean hasError() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.coresdk.v1.ProblemDetail error = 5 [json_name = "error"];</code>
     * @return The error.
     */
    @java.lang.Override
    public coresdk.v1.Common.ProblemDetail getError() {
      return error_ == null ? coresdk.v1.Common.ProblemDetail.getDefaultInstance() : error_;
    }
    /**
     * <code>.coresdk.v1.ProblemDetail error = 5 [json_name = "error"];</code>
     */
    @java.lang.Override
    public coresdk.v1.Common.ProblemDetailOrBuilder getErrorOrBuilder() {
      return error_ == null ? coresdk.v1.Common.ProblemDetail.getDefaultInstance() : error_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (entitled_ != false) {
        output.writeBool(1, entitled_);
      }
      if (numericValue_ != 0L) {
        output.writeInt64(2, numericValue_);
      }
      if (expiresAt_ != 0L) {
        output.writeInt64(3, expiresAt_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(plan_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, plan_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(5, getError());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (entitled_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, entitled_);
      }
      if (numericValue_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, numericValue_);
      }
      if (expiresAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, expiresAt_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(plan_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, plan_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getError());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof coresdk.v1.License.CheckEntitlementResponse)) {
        return super.equals(obj);
      }
      coresdk.v1.License.CheckEntitlementResponse other = (coresdk.v1.License.CheckEntitlementResponse) obj;

      if (getEntitled()
          != other.getEntitled()) return false;
      if (getNumericValue()
          != other.getNumericValue()) return false;
      if (getExpiresAt()
          != other.getExpiresAt()) return false;
      if (!getPlan()
          .equals(other.getPlan())) return false;
      if (hasError() != other.hasError()) return false;
      if (hasError()) {
        if (!getError()
            .equals(other.getError())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ENTITLED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getEntitled());
      hash = (37 * hash) + NUMERIC_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNumericValue());
      hash = (37 * hash) + EXPIRES_AT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExpiresAt());
      hash = (37 * hash) + PLAN_FIELD_NUMBER;
      hash = (53 * hash) + getPlan().hashCode();
      if (hasError()) {
        hash = (37 * hash) + ERROR_FIELD_NUMBER;
        hash = (53 * hash) + getError().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static coresdk.v1.License.CheckEntitlementResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coresdk.v1.License.CheckEntitlementResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coresdk.v1.License.CheckEntitlementResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coresdk.v1.License.CheckEntitlementResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coresdk.v1.License.CheckEntitlementResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coresdk.v1.License.CheckEntitlementResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coresdk.v1.License.CheckEntitlementResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static coresdk.v1.License.CheckEntitlementResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static coresdk.v1.License.CheckEntitlementResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static coresdk.v1.License.CheckEntitlementResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static coresdk.v1.License.CheckEntitlementResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static coresdk.v1.License.CheckEntitlementResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(coresdk.v1.License.CheckEntitlementResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code coresdk.v1.CheckEntitlementResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:coresdk.v1.CheckEntitlementResponse)
        coresdk.v1.License.CheckEntitlementResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return coresdk.v1.License.internal_static_coresdk_v1_CheckEntitlementResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return coresdk.v1.License.internal_static_coresdk_v1_CheckEntitlementResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                coresdk.v1.License.CheckEntitlementResponse.class, coresdk.v1.License.CheckEntitlementResponse.Builder.class);
      }

      // Construct using coresdk.v1.License.CheckEntitlementResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetErrorFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        entitled_ = false;
        numericValue_ = 0L;
        expiresAt_ = 0L;
        plan_ = "";
        error_ = null;
        if (errorBuilder_ != null) {
          errorBuilder_.dispose();
          errorBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return coresdk.v1.License.internal_static_coresdk_v1_CheckEntitlementResponse_descriptor;
      }

      @java.lang.Override
      public coresdk.v1.License.CheckEntitlementResponse getDefaultInstanceForType() {
        return coresdk.v1.License.CheckEntitlementResponse.getDefaultInstance();
      }

      @java.lang.Override
      public coresdk.v1.License.CheckEntitlementResponse build() {
        coresdk.v1.License.CheckEntitlementResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public coresdk.v1.License.CheckEntitlementResponse buildPartial() {
        coresdk.v1.License.CheckEntitlementResponse result = new coresdk.v1.License.CheckEntitlementResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(coresdk.v1.License.CheckEntitlementResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.entitled_ = entitled_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.numericValue_ = numericValue_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.expiresAt_ = expiresAt_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.plan_ = plan_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.error_ = errorBuilder_ == null
              ? error_
              : errorBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof coresdk.v1.License.CheckEntitlementResponse) {
          return mergeFrom((coresdk.v1.License.CheckEntitlementResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(coresdk.v1.License.CheckEntitlementResponse other) {
        if (other == coresdk.v1.License.CheckEntitlementResponse.getDefaultInstance()) return this;
        if (other.getEntitled() != false) {
          setEntitled(other.getEntitled());
        }
        if (other.getNumericValue() != 0L) {
          setNumericValue(other.getNumericValue());
        }
        if (other.getExpiresAt() != 0L) {
          setExpiresAt(other.getExpiresAt());
        }
        if (!other.getPlan().isEmpty()) {
          plan_ = other.plan_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.hasError()) {
          mergeError(other.getError());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                entitled_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                numericValue_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                expiresAt_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                plan_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    internalGetErrorFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean entitled_ ;
      /**
       * <code>bool entitled = 1 [json_name = "entitled"];</code>
       * @return The entitled.
       */
      @java.lang.Override
      public boolean getEntitled() {
        return entitled_;
      }
      /**
       * <code>bool entitled = 1 [json_name = "entitled"];</code>
       * @param value The entitled to set.
       * @return This builder for chaining.
       */
      public Builder setEntitled(boolean value) {

        entitled_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bool entitled = 1 [json_name = "entitled"];</code>
       * @return This builder for chaining.
       */
      public Builder clearEntitled() {
        bitField0_ = (bitField0_ & ~0x00000001);
        entitled_ = false;
        onChanged();
        return this;
      }

      private long numericValue_ ;
      /**
       * <code>int64 numeric_value = 2 [json_name = "numericValue"];</code>
       * @return The numericValue.
       */
      @java.lang.Override
      public long getNumericValue() {
        return numericValue_;
      }
      /**
       * <code>int64 numeric_value = 2 [json_name = "numericValue"];</code>
       * @param value The numericValue to set.
       * @return This builder for chaining.
       */
      public Builder setNumericValue(long value) {

        numericValue_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 numeric_value = 2 [json_name = "numericValue"];</code>
       * @return This builder for chaining.
       */
      public Builder clearNumericValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        numericValue_ = 0L;
        onChanged();
        return this;
      }

      private long expiresAt_ ;
      /**
       * <code>int64 expires_at = 3 [json_name = "expiresAt"];</code>
       * @return The expiresAt.
       */
      @java.lang.Override
      public long getExpiresAt() {
        return expiresAt_;
      }
      /**
       * <code>int64 expires_at = 3 [json_name = "expiresAt"];</code>
       * @param value The expiresAt to set.
       * @return This builder for chaining.
       */
      public Builder setExpiresAt(long value) {

        expiresAt_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 expires_at = 3 [json_name = "expiresAt"];</code>
       * @return This builder for chaining.
       */
      public Builder clearExpiresAt() {
        bitField0_ = (bitField0_ & ~0x00000004);
        expiresAt_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object plan_ = "";
      /**
       * <code>string plan = 4 [json_name = "plan"];</code>
       * @return The plan.
       */
      public java.lang.String getPlan() {
        java.lang.Object ref = plan_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          plan_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string plan = 4 [json_name = "plan"];</code>
       * @return The bytes for plan.
       */
      public com.google.protobuf.ByteString
          getPlanBytes() {
        java.lang.Object ref = plan_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          plan_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string plan = 4 [json_name = "plan"];</code>
       * @param value The plan to set.
       * @return This builder for chaining.
       */
      public Builder setPlan(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        plan_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string plan = 4 [json_name = "plan"];</code>
       * @return This builder for chaining.
       */
      public Builder clearPlan() {
        plan_ = getDefaultInstance().getPlan();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string plan = 4 [json_name = "plan"];</code>
       * @param value The bytes for plan to set.
       * @return This builder for chaining.
       */
      public Builder setPlanBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        plan_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private coresdk.v1.Common.ProblemDetail error_;
      private com.google.protobuf.SingleFieldBuilder<
          coresdk.v1.Common.ProblemDetail, coresdk.v1.Common.ProblemDetail.Builder, coresdk.v1.Common.ProblemDetailOrBuilder> errorBuilder_;
      /**
       * <code>.coresdk.v1.ProblemDetail error = 5 [json_name = "error"];</code>
       * @return Whether the error field is set.
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>.coresdk.v1.ProblemDetail error = 5 [json_name = "error"];</code>
       * @return The error.
       */
      public coresdk.v1.Common.ProblemDetail getError() {
        if (errorBuilder_ == null) {
          return error_ == null ? coresdk.v1.Common.ProblemDetail.getDefaultInstance() : error_;
        } else {
          return errorBuilder_.getMessage();
        }
      }
      /**
       * <code>.coresdk.v1.ProblemDetail error = 5 [json_name = "error"];</code>
       */
      public Builder setError(coresdk.v1.Common.ProblemDetail value) {
        if (errorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          error_ = value;
        } else {
          errorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.coresdk.v1.ProblemDetail error = 5 [json_name = "error"];</code>
       */
      public Builder setError(
          coresdk.v1.Common.ProblemDetail.Builder builderForValue) {
        if (errorBuilder_ == null) {
          error_ = builderForValue.build();
        } else {
          errorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.coresdk.v1.ProblemDetail error = 5 [json_name = "error"];</code>
       */
      public Builder mergeError(coresdk.v1.Common.ProblemDetail value) {
        if (errorBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            error_ != null &&
            error_ != coresdk.v1.Common.ProblemDetail.getDefaultInstance()) {
            getErrorBuilder().mergeFrom(value);
          } else {
            error_ = value;
          }
        } else {
          errorBuilder_.mergeFrom(value);
        }
        if (error_ != null) {
          bitField0_ |= 0x00000010;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.coresdk.v1.ProblemDetail error = 5 [json_name = "error"];</code>
       */
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000010);
        error_ = null;
        if (errorBuilder_ != null) {
          errorBuilder_.dispose();
          errorBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.coresdk.v1.ProblemDetail error = 5 [json_name = "error"];</code>
       */
      public coresdk.v1.Common.ProblemDetail.Builder getErrorBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return internalGetErrorFieldBuilder().getBuilder();
      }
      /**
       * <code>.coresdk.v1.ProblemDetail error = 5 [json_name = "error"];</code>
       */
      public coresdk.v1.Common.ProblemDetailOrBuilder getErrorOrBuilder() {
        if (errorBuilder_ != null) {
          return errorBuilder_.getMessageOrBuilder();
        } else {
          return error_ == null ?
              coresdk.v1.Common.ProblemDetail.getDefaultInstance() : error_;
        }
      }
      /**
       * <code>.coresdk.v1.ProblemDetail error = 5 [json_name = "error"];</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          coresdk.v1.Common.ProblemDetail, coresdk.v1.Common.ProblemDetail.Builder, coresdk.v1.Common.ProblemDetailOrBuilder> 
          internalGetErrorFieldBuilder() {
        if (errorBuilder_ == null) {
          errorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              coresdk.v1.Common.ProblemDetail, coresdk.v1.Common.ProblemDetail.Builder, coresdk.v1.Common.ProblemDetailOrBuilder>(
                  getError(),
                  getParentForChildren(),
                  isClean());
          error_ = null;
        }
        return errorBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:coresdk.v1.CheckEntitlementResponse)
    }

    // @@protoc_insertion_point(class_scope:coresdk.v1.CheckEntitlementResponse)
    private static final coresdk.v1.License.CheckEntitlementResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new coresdk.v1.License.CheckEntitlementResponse();
    }

    public static coresdk.v1.License.CheckEntitlementResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CheckEntitlementResponse>
        PARSER = new com.google.protobuf.AbstractParser<CheckEntitlementResponse>() {
      @java.lang.Override
      public CheckEntitlementResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CheckEntitlementResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CheckEntitlementResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public coresdk.v1.License.CheckEntitlementResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coresdk_v1_CheckEntitlementRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_coresdk_v1_CheckEntitlementRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coresdk_v1_CheckEntitlementResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_coresdk_v1_CheckEntitlementResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030coresdk/v1/license.proto\022\ncoresdk.v1\032\027" +
      "coresdk/v1/common.proto\"_\n\027CheckEntitlem" +
      "entRequest\022\'\n\017entitlement_key\030\001 \001(\tR\016ent" +
      "itlementKey\022\033\n\ttenant_id\030\002 \001(\tR\010tenantId" +
      "\"\277\001\n\030CheckEntitlementResponse\022\032\n\010entitle" +
      "d\030\001 \001(\010R\010entitled\022#\n\rnumeric_value\030\002 \001(\003" +
      "R\014numericValue\022\035\n\nexpires_at\030\003 \001(\003R\texpi" +
      "resAt\022\022\n\004plan\030\004 \001(\tR\004plan\022/\n\005error\030\005 \001(\013" +
      "2\031.coresdk.v1.ProblemDetailR\005error2o\n\016Li" +
      "censeService\022]\n\020CheckEntitlement\022#.cores" +
      "dk.v1.CheckEntitlementRequest\032$.coresdk." +
      "v1.CheckEntitlementResponseB.Z,github.co" +
      "m/coresdk-dev/sdk-go/gen/coresdk/v1b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          coresdk.v1.Common.getDescriptor(),
        });
    internal_static_coresdk_v1_CheckEntitlementRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_coresdk_v1_CheckEntitlementRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_coresdk_v1_CheckEntitlementRequest_descriptor,
        new java.lang.String[] { "EntitlementKey", "TenantId", });
    internal_static_coresdk_v1_CheckEntitlementResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_coresdk_v1_CheckEntitlementResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_coresdk_v1_CheckEntitlementResponse_descriptor,
        new java.lang.String[] { "Entitled", "NumericValue", "ExpiresAt", "Plan", "Error", });
    descriptor.resolveAllFeaturesImmutable();
    coresdk.v1.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
