// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: coresdk/v1/ratelimit.proto
// Protobuf Java Version: 4.34.1

package coresdk.v1;

@com.google.protobuf.Generated
public final class Ratelimit extends com.google.protobuf.GeneratedFile {
  private Ratelimit() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "Ratelimit");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CheckRateLimitRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:coresdk.v1.CheckRateLimitRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return The tenantId.
     */
    java.lang.String getTenantId();
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return The bytes for tenantId.
     */
    com.google.protobuf.ByteString
        getTenantIdBytes();

    /**
     * <code>uint32 limit = 3 [json_name = "limit"];</code>
     * @return The limit.
     */
    int getLimit();

    /**
     * <code>uint32 window_seconds = 4 [json_name = "windowSeconds"];</code>
     * @return The windowSeconds.
     */
    int getWindowSeconds();
  }
  /**
   * Protobuf type {@code coresdk.v1.CheckRateLimitRequest}
   */
  public static final class CheckRateLimitRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:coresdk.v1.CheckRateLimitRequest)
      CheckRateLimitRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 1,
        /* suffix= */ "",
        "CheckRateLimitRequest");
    }
    // Use CheckRateLimitRequest.newBuilder() to construct.
    private CheckRateLimitRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CheckRateLimitRequest() {
      key_ = "";
      tenantId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return coresdk.v1.Ratelimit.internal_static_coresdk_v1_CheckRateLimitRequest_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return coresdk.v1.Ratelimit.internal_static_coresdk_v1_CheckRateLimitRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return coresdk.v1.Ratelimit.internal_static_coresdk_v1_CheckRateLimitRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              coresdk.v1.Ratelimit.CheckRateLimitRequest.class, coresdk.v1.Ratelimit.CheckRateLimitRequest.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object key_ = "";
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TENANT_ID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object tenantId_ = "";
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return The tenantId.
     */
    @java.lang.Override
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      }
    }
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return The bytes for tenantId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LIMIT_FIELD_NUMBER = 3;
    private int limit_ = 0;
    /**
     * <code>uint32 limit = 3 [json_name = "limit"];</code>
     * @return The limit.
     */
    @java.lang.Override
    public int getLimit() {
      return limit_;
    }

    public static final int WINDOW_SECONDS_FIELD_NUMBER = 4;
    private int windowSeconds_ = 0;
    /**
     * <code>uint32 window_seconds = 4 [json_name = "windowSeconds"];</code>
     * @return The windowSeconds.
     */
    @java.lang.Override
    public int getWindowSeconds() {
      return windowSeconds_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(key_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, key_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, tenantId_);
      }
      if (limit_ != 0) {
        output.writeUInt32(3, limit_);
      }
      if (windowSeconds_ != 0) {
        output.writeUInt32(4, windowSeconds_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(key_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, key_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, tenantId_);
      }
      if (limit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, limit_);
      }
      if (windowSeconds_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, windowSeconds_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof coresdk.v1.Ratelimit.CheckRateLimitRequest)) {
        return super.equals(obj);
      }
      coresdk.v1.Ratelimit.CheckRateLimitRequest other = (coresdk.v1.Ratelimit.CheckRateLimitRequest) obj;

      if (!getKey()
          .equals(other.getKey())) return false;
      if (!getTenantId()
          .equals(other.getTenantId())) return false;
      if (getLimit()
          != other.getLimit()) return false;
      if (getWindowSeconds()
          != other.getWindowSeconds()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTenantId().hashCode();
      hash = (37 * hash) + LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getLimit();
      hash = (37 * hash) + WINDOW_SECONDS_FIELD_NUMBER;
      hash = (53 * hash) + getWindowSeconds();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static coresdk.v1.Ratelimit.CheckRateLimitRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coresdk.v1.Ratelimit.CheckRateLimitRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coresdk.v1.Ratelimit.CheckRateLimitRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coresdk.v1.Ratelimit.CheckRateLimitRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coresdk.v1.Ratelimit.CheckRateLimitRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coresdk.v1.Ratelimit.CheckRateLimitRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coresdk.v1.Ratelimit.CheckRateLimitRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static coresdk.v1.Ratelimit.CheckRateLimitRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static coresdk.v1.Ratelimit.CheckRateLimitRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static coresdk.v1.Ratelimit.CheckRateLimitRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static coresdk.v1.Ratelimit.CheckRateLimitRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static coresdk.v1.Ratelimit.CheckRateLimitRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(coresdk.v1.Ratelimit.CheckRateLimitRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code coresdk.v1.CheckRateLimitRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:coresdk.v1.CheckRateLimitRequest)
        coresdk.v1.Ratelimit.CheckRateLimitRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return coresdk.v1.Ratelimit.internal_static_coresdk_v1_CheckRateLimitRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return coresdk.v1.Ratelimit.internal_static_coresdk_v1_CheckRateLimitRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                coresdk.v1.Ratelimit.CheckRateLimitRequest.class, coresdk.v1.Ratelimit.CheckRateLimitRequest.Builder.class);
      }

      // Construct using coresdk.v1.Ratelimit.CheckRateLimitRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        key_ = "";
        tenantId_ = "";
        limit_ = 0;
        windowSeconds_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return coresdk.v1.Ratelimit.internal_static_coresdk_v1_CheckRateLimitRequest_descriptor;
      }

      @java.lang.Override
      public coresdk.v1.Ratelimit.CheckRateLimitRequest getDefaultInstanceForType() {
        return coresdk.v1.Ratelimit.CheckRateLimitRequest.getDefaultInstance();
      }

      @java.lang.Override
      public coresdk.v1.Ratelimit.CheckRateLimitRequest build() {
        coresdk.v1.Ratelimit.CheckRateLimitRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public coresdk.v1.Ratelimit.CheckRateLimitRequest buildPartial() {
        coresdk.v1.Ratelimit.CheckRateLimitRequest result = new coresdk.v1.Ratelimit.CheckRateLimitRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(coresdk.v1.Ratelimit.CheckRateLimitRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.key_ = key_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.tenantId_ = tenantId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.limit_ = limit_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.windowSeconds_ = windowSeconds_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof coresdk.v1.Ratelimit.CheckRateLimitRequest) {
          return mergeFrom((coresdk.v1.Ratelimit.CheckRateLimitRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(coresdk.v1.Ratelimit.CheckRateLimitRequest other) {
        if (other == coresdk.v1.Ratelimit.CheckRateLimitRequest.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getTenantId().isEmpty()) {
          tenantId_ = other.tenantId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getLimit() != 0) {
          setLimit(other.getLimit());
        }
        if (other.getWindowSeconds() != 0) {
          setWindowSeconds(other.getWindowSeconds());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                key_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                tenantId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                limit_ = input.readUInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                windowSeconds_ = input.readUInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 1 [json_name = "key"];</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 1 [json_name = "key"];</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 1 [json_name = "key"];</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        key_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1 [json_name = "key"];</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        key_ = getDefaultInstance().getKey();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1 [json_name = "key"];</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        key_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object tenantId_ = "";
      /**
       * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
       * @return The tenantId.
       */
      public java.lang.String getTenantId() {
        java.lang.Object ref = tenantId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tenantId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
       * @return The bytes for tenantId.
       */
      public com.google.protobuf.ByteString
          getTenantIdBytes() {
        java.lang.Object ref = tenantId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tenantId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
       * @param value The tenantId to set.
       * @return This builder for chaining.
       */
      public Builder setTenantId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        tenantId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearTenantId() {
        tenantId_ = getDefaultInstance().getTenantId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
       * @param value The bytes for tenantId to set.
       * @return This builder for chaining.
       */
      public Builder setTenantIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        tenantId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int limit_ ;
      /**
       * <code>uint32 limit = 3 [json_name = "limit"];</code>
       * @return The limit.
       */
      @java.lang.Override
      public int getLimit() {
        return limit_;
      }
      /**
       * <code>uint32 limit = 3 [json_name = "limit"];</code>
       * @param value The limit to set.
       * @return This builder for chaining.
       */
      public Builder setLimit(int value) {

        limit_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 limit = 3 [json_name = "limit"];</code>
       * @return This builder for chaining.
       */
      public Builder clearLimit() {
        bitField0_ = (bitField0_ & ~0x00000004);
        limit_ = 0;
        onChanged();
        return this;
      }

      private int windowSeconds_ ;
      /**
       * <code>uint32 window_seconds = 4 [json_name = "windowSeconds"];</code>
       * @return The windowSeconds.
       */
      @java.lang.Override
      public int getWindowSeconds() {
        return windowSeconds_;
      }
      /**
       * <code>uint32 window_seconds = 4 [json_name = "windowSeconds"];</code>
       * @param value The windowSeconds to set.
       * @return This builder for chaining.
       */
      public Builder setWindowSeconds(int value) {

        windowSeconds_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 window_seconds = 4 [json_name = "windowSeconds"];</code>
       * @return This builder for chaining.
       */
      public Builder clearWindowSeconds() {
        bitField0_ = (bitField0_ & ~0x00000008);
        windowSeconds_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:coresdk.v1.CheckRateLimitRequest)
    }

    // @@protoc_insertion_point(class_scope:coresdk.v1.CheckRateLimitRequest)
    private static final coresdk.v1.Ratelimit.CheckRateLimitRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new coresdk.v1.Ratelimit.CheckRateLimitRequest();
    }

    public static coresdk.v1.Ratelimit.CheckRateLimitRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CheckRateLimitRequest>
        PARSER = new com.google.protobuf.AbstractParser<CheckRateLimitRequest>() {
      @java.lang.Override
      public CheckRateLimitRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CheckRateLimitRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CheckRateLimitRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public coresdk.v1.Ratelimit.CheckRateLimitRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CheckRateLimitResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:coresdk.v1.CheckRateLimitResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool allowed = 1 [json_name = "allowed"];</code>
     * @return The allowed.
     */
    boolean getAllowed();

    /**
     * <code>uint32 remaining = 2 [json_name = "remaining"];</code>
     * @return The remaining.
     */
    int getRemaining();

    /**
     * <code>uint64 retry_after_ms = 3 [json_name = "retryAfterMs"];</code>
     * @return The retryAfterMs.
     */
    long getRetryAfterMs();

    /**
     * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
     * @return Whether the error field is set.
     */
    boolean hasError();
    /**
     * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
     * @return The error.
     */
    coresdk.v1.Common.ProblemDetail getError();
    /**
     * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
     */
    coresdk.v1.Common.ProblemDetailOrBuilder getErrorOrBuilder();
  }
  /**
   * Protobuf type {@code coresdk.v1.CheckRateLimitResponse}
   */
  public static final class CheckRateLimitResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:coresdk.v1.CheckRateLimitResponse)
      CheckRateLimitResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 1,
        /* suffix= */ "",
        "CheckRateLimitResponse");
    }
    // Use CheckRateLimitResponse.newBuilder() to construct.
    private CheckRateLimitResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CheckRateLimitResponse() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return coresdk.v1.Ratelimit.internal_static_coresdk_v1_CheckRateLimitResponse_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return coresdk.v1.Ratelimit.internal_static_coresdk_v1_CheckRateLimitResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return coresdk.v1.Ratelimit.internal_static_coresdk_v1_CheckRateLimitResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              coresdk.v1.Ratelimit.CheckRateLimitResponse.class, coresdk.v1.Ratelimit.CheckRateLimitResponse.Builder.class);
    }

    private int bitField0_;
    public static final int ALLOWED_FIELD_NUMBER = 1;
    private boolean allowed_ = false;
    /**
     * <code>bool allowed = 1 [json_name = "allowed"];</code>
     * @return The allowed.
     */
    @java.lang.Override
    public boolean getAllowed() {
      return allowed_;
    }

    public static final int REMAINING_FIELD_NUMBER = 2;
    private int remaining_ = 0;
    /**
     * <code>uint32 remaining = 2 [json_name = "remaining"];</code>
     * @return The remaining.
     */
    @java.lang.Override
    public int getRemaining() {
      return remaining_;
    }

    public static final int RETRY_AFTER_MS_FIELD_NUMBER = 3;
    private long retryAfterMs_ = 0L;
    /**
     * <code>uint64 retry_after_ms = 3 [json_name = "retryAfterMs"];</code>
     * @return The retryAfterMs.
     */
    @java.lang.Override
    public long getRetryAfterMs() {
      return retryAfterMs_;
    }

    public static final int ERROR_FIELD_NUMBER = 4;
    private coresdk.v1.Common.ProblemDetail error_;
    /**
     * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
     * @return Whether the error field is set.
     */
    @java.lang.Override
    public boolean hasError() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
     * @return The error.
     */
    @java.lang.Override
    public coresdk.v1.Common.ProblemDetail getError() {
      return error_ == null ? coresdk.v1.Common.ProblemDetail.getDefaultInstance() : error_;
    }
    /**
     * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
     */
    @java.lang.Override
    public coresdk.v1.Common.ProblemDetailOrBuilder getErrorOrBuilder() {
      return error_ == null ? coresdk.v1.Common.ProblemDetail.getDefaultInstance() : error_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (allowed_ != false) {
        output.writeBool(1, allowed_);
      }
      if (remaining_ != 0) {
        output.writeUInt32(2, remaining_);
      }
      if (retryAfterMs_ != 0L) {
        output.writeUInt64(3, retryAfterMs_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(4, getError());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (allowed_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, allowed_);
      }
      if (remaining_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, remaining_);
      }
      if (retryAfterMs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, retryAfterMs_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getError());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof coresdk.v1.Ratelimit.CheckRateLimitResponse)) {
        return super.equals(obj);
      }
      coresdk.v1.Ratelimit.CheckRateLimitResponse other = (coresdk.v1.Ratelimit.CheckRateLimitResponse) obj;

      if (getAllowed()
          != other.getAllowed()) return false;
      if (getRemaining()
          != other.getRemaining()) return false;
      if (getRetryAfterMs()
          != other.getRetryAfterMs()) return false;
      if (hasError() != other.hasError()) return false;
      if (hasError()) {
        if (!getError()
            .equals(other.getError())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ALLOWED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAllowed());
      hash = (37 * hash) + REMAINING_FIELD_NUMBER;
      hash = (53 * hash) + getRemaining();
      hash = (37 * hash) + RETRY_AFTER_MS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRetryAfterMs());
      if (hasError()) {
        hash = (37 * hash) + ERROR_FIELD_NUMBER;
        hash = (53 * hash) + getError().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static coresdk.v1.Ratelimit.CheckRateLimitResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coresdk.v1.Ratelimit.CheckRateLimitResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coresdk.v1.Ratelimit.CheckRateLimitResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coresdk.v1.Ratelimit.CheckRateLimitResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coresdk.v1.Ratelimit.CheckRateLimitResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coresdk.v1.Ratelimit.CheckRateLimitResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coresdk.v1.Ratelimit.CheckRateLimitResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static coresdk.v1.Ratelimit.CheckRateLimitResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static coresdk.v1.Ratelimit.CheckRateLimitResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static coresdk.v1.Ratelimit.CheckRateLimitResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static coresdk.v1.Ratelimit.CheckRateLimitResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static coresdk.v1.Ratelimit.CheckRateLimitResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(coresdk.v1.Ratelimit.CheckRateLimitResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code coresdk.v1.CheckRateLimitResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:coresdk.v1.CheckRateLimitResponse)
        coresdk.v1.Ratelimit.CheckRateLimitResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return coresdk.v1.Ratelimit.internal_static_coresdk_v1_CheckRateLimitResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return coresdk.v1.Ratelimit.internal_static_coresdk_v1_CheckRateLimitResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                coresdk.v1.Ratelimit.CheckRateLimitResponse.class, coresdk.v1.Ratelimit.CheckRateLimitResponse.Builder.class);
      }

      // Construct using coresdk.v1.Ratelimit.CheckRateLimitResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetErrorFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        allowed_ = false;
        remaining_ = 0;
        retryAfterMs_ = 0L;
        error_ = null;
        if (errorBuilder_ != null) {
          errorBuilder_.dispose();
          errorBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return coresdk.v1.Ratelimit.internal_static_coresdk_v1_CheckRateLimitResponse_descriptor;
      }

      @java.lang.Override
      public coresdk.v1.Ratelimit.CheckRateLimitResponse getDefaultInstanceForType() {
        return coresdk.v1.Ratelimit.CheckRateLimitResponse.getDefaultInstance();
      }

      @java.lang.Override
      public coresdk.v1.Ratelimit.CheckRateLimitResponse build() {
        coresdk.v1.Ratelimit.CheckRateLimitResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public coresdk.v1.Ratelimit.CheckRateLimitResponse buildPartial() {
        coresdk.v1.Ratelimit.CheckRateLimitResponse result = new coresdk.v1.Ratelimit.CheckRateLimitResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(coresdk.v1.Ratelimit.CheckRateLimitResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.allowed_ = allowed_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.remaining_ = remaining_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.retryAfterMs_ = retryAfterMs_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.error_ = errorBuilder_ == null
              ? error_
              : errorBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof coresdk.v1.Ratelimit.CheckRateLimitResponse) {
          return mergeFrom((coresdk.v1.Ratelimit.CheckRateLimitResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(coresdk.v1.Ratelimit.CheckRateLimitResponse other) {
        if (other == coresdk.v1.Ratelimit.CheckRateLimitResponse.getDefaultInstance()) return this;
        if (other.getAllowed() != false) {
          setAllowed(other.getAllowed());
        }
        if (other.getRemaining() != 0) {
          setRemaining(other.getRemaining());
        }
        if (other.getRetryAfterMs() != 0L) {
          setRetryAfterMs(other.getRetryAfterMs());
        }
        if (other.hasError()) {
          mergeError(other.getError());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                allowed_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                remaining_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                retryAfterMs_ = input.readUInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                input.readMessage(
                    internalGetErrorFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean allowed_ ;
      /**
       * <code>bool allowed = 1 [json_name = "allowed"];</code>
       * @return The allowed.
       */
      @java.lang.Override
      public boolean getAllowed() {
        return allowed_;
      }
      /**
       * <code>bool allowed = 1 [json_name = "allowed"];</code>
       * @param value The allowed to set.
       * @return This builder for chaining.
       */
      public Builder setAllowed(boolean value) {

        allowed_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bool allowed = 1 [json_name = "allowed"];</code>
       * @return This builder for chaining.
       */
      public Builder clearAllowed() {
        bitField0_ = (bitField0_ & ~0x00000001);
        allowed_ = false;
        onChanged();
        return this;
      }

      private int remaining_ ;
      /**
       * <code>uint32 remaining = 2 [json_name = "remaining"];</code>
       * @return The remaining.
       */
      @java.lang.Override
      public int getRemaining() {
        return remaining_;
      }
      /**
       * <code>uint32 remaining = 2 [json_name = "remaining"];</code>
       * @param value The remaining to set.
       * @return This builder for chaining.
       */
      public Builder setRemaining(int value) {

        remaining_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 remaining = 2 [json_name = "remaining"];</code>
       * @return This builder for chaining.
       */
      public Builder clearRemaining() {
        bitField0_ = (bitField0_ & ~0x00000002);
        remaining_ = 0;
        onChanged();
        return this;
      }

      private long retryAfterMs_ ;
      /**
       * <code>uint64 retry_after_ms = 3 [json_name = "retryAfterMs"];</code>
       * @return The retryAfterMs.
       */
      @java.lang.Override
      public long getRetryAfterMs() {
        return retryAfterMs_;
      }
      /**
       * <code>uint64 retry_after_ms = 3 [json_name = "retryAfterMs"];</code>
       * @param value The retryAfterMs to set.
       * @return This builder for chaining.
       */
      public Builder setRetryAfterMs(long value) {

        retryAfterMs_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 retry_after_ms = 3 [json_name = "retryAfterMs"];</code>
       * @return This builder for chaining.
       */
      public Builder clearRetryAfterMs() {
        bitField0_ = (bitField0_ & ~0x00000004);
        retryAfterMs_ = 0L;
        onChanged();
        return this;
      }

      private coresdk.v1.Common.ProblemDetail error_;
      private com.google.protobuf.SingleFieldBuilder<
          coresdk.v1.Common.ProblemDetail, coresdk.v1.Common.ProblemDetail.Builder, coresdk.v1.Common.ProblemDetailOrBuilder> errorBuilder_;
      /**
       * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
       * @return Whether the error field is set.
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
       * @return The error.
       */
      public coresdk.v1.Common.ProblemDetail getError() {
        if (errorBuilder_ == null) {
          return error_ == null ? coresdk.v1.Common.ProblemDetail.getDefaultInstance() : error_;
        } else {
          return errorBuilder_.getMessage();
        }
      }
      /**
       * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
       */
      public Builder setError(coresdk.v1.Common.ProblemDetail value) {
        if (errorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          error_ = value;
        } else {
          errorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
       */
      public Builder setError(
          coresdk.v1.Common.ProblemDetail.Builder builderForValue) {
        if (errorBuilder_ == null) {
          error_ = builderForValue.build();
        } else {
          errorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
       */
      public Builder mergeError(coresdk.v1.Common.ProblemDetail value) {
        if (errorBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            error_ != null &&
            error_ != coresdk.v1.Common.ProblemDetail.getDefaultInstance()) {
            getErrorBuilder().mergeFrom(value);
          } else {
            error_ = value;
          }
        } else {
          errorBuilder_.mergeFrom(value);
        }
        if (error_ != null) {
          bitField0_ |= 0x00000008;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
       */
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000008);
        error_ = null;
        if (errorBuilder_ != null) {
          errorBuilder_.dispose();
          errorBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
       */
      public coresdk.v1.Common.ProblemDetail.Builder getErrorBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return internalGetErrorFieldBuilder().getBuilder();
      }
      /**
       * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
       */
      public coresdk.v1.Common.ProblemDetailOrBuilder getErrorOrBuilder() {
        if (errorBuilder_ != null) {
          return errorBuilder_.getMessageOrBuilder();
        } else {
          return error_ == null ?
              coresdk.v1.Common.ProblemDetail.getDefaultInstance() : error_;
        }
      }
      /**
       * <code>.coresdk.v1.ProblemDetail error = 4 [json_name = "error"];</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          coresdk.v1.Common.ProblemDetail, coresdk.v1.Common.ProblemDetail.Builder, coresdk.v1.Common.ProblemDetailOrBuilder> 
          internalGetErrorFieldBuilder() {
        if (errorBuilder_ == null) {
          errorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              coresdk.v1.Common.ProblemDetail, coresdk.v1.Common.ProblemDetail.Builder, coresdk.v1.Common.ProblemDetailOrBuilder>(
                  getError(),
                  getParentForChildren(),
                  isClean());
          error_ = null;
        }
        return errorBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:coresdk.v1.CheckRateLimitResponse)
    }

    // @@protoc_insertion_point(class_scope:coresdk.v1.CheckRateLimitResponse)
    private static final coresdk.v1.Ratelimit.CheckRateLimitResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new coresdk.v1.Ratelimit.CheckRateLimitResponse();
    }

    public static coresdk.v1.Ratelimit.CheckRateLimitResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CheckRateLimitResponse>
        PARSER = new com.google.protobuf.AbstractParser<CheckRateLimitResponse>() {
      @java.lang.Override
      public CheckRateLimitResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CheckRateLimitResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CheckRateLimitResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public coresdk.v1.Ratelimit.CheckRateLimitResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResetRateLimitRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:coresdk.v1.ResetRateLimitRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return The tenantId.
     */
    java.lang.String getTenantId();
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return The bytes for tenantId.
     */
    com.google.protobuf.ByteString
        getTenantIdBytes();
  }
  /**
   * Protobuf type {@code coresdk.v1.ResetRateLimitRequest}
   */
  public static final class ResetRateLimitRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:coresdk.v1.ResetRateLimitRequest)
      ResetRateLimitRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 1,
        /* suffix= */ "",
        "ResetRateLimitRequest");
    }
    // Use ResetRateLimitRequest.newBuilder() to construct.
    private ResetRateLimitRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResetRateLimitRequest() {
      key_ = "";
      tenantId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return coresdk.v1.Ratelimit.internal_static_coresdk_v1_ResetRateLimitRequest_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return coresdk.v1.Ratelimit.internal_static_coresdk_v1_ResetRateLimitRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return coresdk.v1.Ratelimit.internal_static_coresdk_v1_ResetRateLimitRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              coresdk.v1.Ratelimit.ResetRateLimitRequest.class, coresdk.v1.Ratelimit.ResetRateLimitRequest.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object key_ = "";
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TENANT_ID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object tenantId_ = "";
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return The tenantId.
     */
    @java.lang.Override
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      }
    }
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return The bytes for tenantId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(key_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, key_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, tenantId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(key_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, key_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, tenantId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof coresdk.v1.Ratelimit.ResetRateLimitRequest)) {
        return super.equals(obj);
      }
      coresdk.v1.Ratelimit.ResetRateLimitRequest other = (coresdk.v1.Ratelimit.ResetRateLimitRequest) obj;

      if (!getKey()
          .equals(other.getKey())) return false;
      if (!getTenantId()
          .equals(other.getTenantId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTenantId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static coresdk.v1.Ratelimit.ResetRateLimitRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coresdk.v1.Ratelimit.ResetRateLimitRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coresdk.v1.Ratelimit.ResetRateLimitRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coresdk.v1.Ratelimit.ResetRateLimitRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coresdk.v1.Ratelimit.ResetRateLimitRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coresdk.v1.Ratelimit.ResetRateLimitRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coresdk.v1.Ratelimit.ResetRateLimitRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static coresdk.v1.Ratelimit.ResetRateLimitRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static coresdk.v1.Ratelimit.ResetRateLimitRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static coresdk.v1.Ratelimit.ResetRateLimitRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static coresdk.v1.Ratelimit.ResetRateLimitRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static coresdk.v1.Ratelimit.ResetRateLimitRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(coresdk.v1.Ratelimit.ResetRateLimitRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code coresdk.v1.ResetRateLimitRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:coresdk.v1.ResetRateLimitRequest)
        coresdk.v1.Ratelimit.ResetRateLimitRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return coresdk.v1.Ratelimit.internal_static_coresdk_v1_ResetRateLimitRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return coresdk.v1.Ratelimit.internal_static_coresdk_v1_ResetRateLimitRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                coresdk.v1.Ratelimit.ResetRateLimitRequest.class, coresdk.v1.Ratelimit.ResetRateLimitRequest.Builder.class);
      }

      // Construct using coresdk.v1.Ratelimit.ResetRateLimitRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        key_ = "";
        tenantId_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return coresdk.v1.Ratelimit.internal_static_coresdk_v1_ResetRateLimitRequest_descriptor;
      }

      @java.lang.Override
      public coresdk.v1.Ratelimit.ResetRateLimitRequest getDefaultInstanceForType() {
        return coresdk.v1.Ratelimit.ResetRateLimitRequest.getDefaultInstance();
      }

      @java.lang.Override
      public coresdk.v1.Ratelimit.ResetRateLimitRequest build() {
        coresdk.v1.Ratelimit.ResetRateLimitRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public coresdk.v1.Ratelimit.ResetRateLimitRequest buildPartial() {
        coresdk.v1.Ratelimit.ResetRateLimitRequest result = new coresdk.v1.Ratelimit.ResetRateLimitRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(coresdk.v1.Ratelimit.ResetRateLimitRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.key_ = key_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.tenantId_ = tenantId_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof coresdk.v1.Ratelimit.ResetRateLimitRequest) {
          return mergeFrom((coresdk.v1.Ratelimit.ResetRateLimitRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(coresdk.v1.Ratelimit.ResetRateLimitRequest other) {
        if (other == coresdk.v1.Ratelimit.ResetRateLimitRequest.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getTenantId().isEmpty()) {
          tenantId_ = other.tenantId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                key_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                tenantId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 1 [json_name = "key"];</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 1 [json_name = "key"];</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 1 [json_name = "key"];</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        key_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1 [json_name = "key"];</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        key_ = getDefaultInstance().getKey();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1 [json_name = "key"];</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        key_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object tenantId_ = "";
      /**
       * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
       * @return The tenantId.
       */
      public java.lang.String getTenantId() {
        java.lang.Object ref = tenantId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tenantId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
       * @return The bytes for tenantId.
       */
      public com.google.protobuf.ByteString
          getTenantIdBytes() {
        java.lang.Object ref = tenantId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tenantId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
       * @param value The tenantId to set.
       * @return This builder for chaining.
       */
      public Builder setTenantId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        tenantId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearTenantId() {
        tenantId_ = getDefaultInstance().getTenantId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
       * @param value The bytes for tenantId to set.
       * @return This builder for chaining.
       */
      public Builder setTenantIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        tenantId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:coresdk.v1.ResetRateLimitRequest)
    }

    // @@protoc_insertion_point(class_scope:coresdk.v1.ResetRateLimitRequest)
    private static final coresdk.v1.Ratelimit.ResetRateLimitRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new coresdk.v1.Ratelimit.ResetRateLimitRequest();
    }

    public static coresdk.v1.Ratelimit.ResetRateLimitRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResetRateLimitRequest>
        PARSER = new com.google.protobuf.AbstractParser<ResetRateLimitRequest>() {
      @java.lang.Override
      public ResetRateLimitRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResetRateLimitRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResetRateLimitRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public coresdk.v1.Ratelimit.ResetRateLimitRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResetRateLimitResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:coresdk.v1.ResetRateLimitResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1 [json_name = "success"];</code>
     * @return The success.
     */
    boolean getSuccess();
  }
  /**
   * Protobuf type {@code coresdk.v1.ResetRateLimitResponse}
   */
  public static final class ResetRateLimitResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:coresdk.v1.ResetRateLimitResponse)
      ResetRateLimitResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 1,
        /* suffix= */ "",
        "ResetRateLimitResponse");
    }
    // Use ResetRateLimitResponse.newBuilder() to construct.
    private ResetRateLimitResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResetRateLimitResponse() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return coresdk.v1.Ratelimit.internal_static_coresdk_v1_ResetRateLimitResponse_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return coresdk.v1.Ratelimit.internal_static_coresdk_v1_ResetRateLimitResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return coresdk.v1.Ratelimit.internal_static_coresdk_v1_ResetRateLimitResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              coresdk.v1.Ratelimit.ResetRateLimitResponse.class, coresdk.v1.Ratelimit.ResetRateLimitResponse.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_ = false;
    /**
     * <code>bool success = 1 [json_name = "success"];</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof coresdk.v1.Ratelimit.ResetRateLimitResponse)) {
        return super.equals(obj);
      }
      coresdk.v1.Ratelimit.ResetRateLimitResponse other = (coresdk.v1.Ratelimit.ResetRateLimitResponse) obj;

      if (getSuccess()
          != other.getSuccess()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static coresdk.v1.Ratelimit.ResetRateLimitResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coresdk.v1.Ratelimit.ResetRateLimitResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coresdk.v1.Ratelimit.ResetRateLimitResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coresdk.v1.Ratelimit.ResetRateLimitResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coresdk.v1.Ratelimit.ResetRateLimitResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coresdk.v1.Ratelimit.ResetRateLimitResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coresdk.v1.Ratelimit.ResetRateLimitResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static coresdk.v1.Ratelimit.ResetRateLimitResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static coresdk.v1.Ratelimit.ResetRateLimitResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static coresdk.v1.Ratelimit.ResetRateLimitResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static coresdk.v1.Ratelimit.ResetRateLimitResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static coresdk.v1.Ratelimit.ResetRateLimitResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(coresdk.v1.Ratelimit.ResetRateLimitResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code coresdk.v1.ResetRateLimitResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:coresdk.v1.ResetRateLimitResponse)
        coresdk.v1.Ratelimit.ResetRateLimitResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return coresdk.v1.Ratelimit.internal_static_coresdk_v1_ResetRateLimitResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return coresdk.v1.Ratelimit.internal_static_coresdk_v1_ResetRateLimitResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                coresdk.v1.Ratelimit.ResetRateLimitResponse.class, coresdk.v1.Ratelimit.ResetRateLimitResponse.Builder.class);
      }

      // Construct using coresdk.v1.Ratelimit.ResetRateLimitResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        success_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return coresdk.v1.Ratelimit.internal_static_coresdk_v1_ResetRateLimitResponse_descriptor;
      }

      @java.lang.Override
      public coresdk.v1.Ratelimit.ResetRateLimitResponse getDefaultInstanceForType() {
        return coresdk.v1.Ratelimit.ResetRateLimitResponse.getDefaultInstance();
      }

      @java.lang.Override
      public coresdk.v1.Ratelimit.ResetRateLimitResponse build() {
        coresdk.v1.Ratelimit.ResetRateLimitResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public coresdk.v1.Ratelimit.ResetRateLimitResponse buildPartial() {
        coresdk.v1.Ratelimit.ResetRateLimitResponse result = new coresdk.v1.Ratelimit.ResetRateLimitResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(coresdk.v1.Ratelimit.ResetRateLimitResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.success_ = success_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof coresdk.v1.Ratelimit.ResetRateLimitResponse) {
          return mergeFrom((coresdk.v1.Ratelimit.ResetRateLimitResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(coresdk.v1.Ratelimit.ResetRateLimitResponse other) {
        if (other == coresdk.v1.Ratelimit.ResetRateLimitResponse.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                success_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean success_ ;
      /**
       * <code>bool success = 1 [json_name = "success"];</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 1 [json_name = "success"];</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {

        success_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 1 [json_name = "success"];</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        success_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:coresdk.v1.ResetRateLimitResponse)
    }

    // @@protoc_insertion_point(class_scope:coresdk.v1.ResetRateLimitResponse)
    private static final coresdk.v1.Ratelimit.ResetRateLimitResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new coresdk.v1.Ratelimit.ResetRateLimitResponse();
    }

    public static coresdk.v1.Ratelimit.ResetRateLimitResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResetRateLimitResponse>
        PARSER = new com.google.protobuf.AbstractParser<ResetRateLimitResponse>() {
      @java.lang.Override
      public ResetRateLimitResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResetRateLimitResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResetRateLimitResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public coresdk.v1.Ratelimit.ResetRateLimitResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coresdk_v1_CheckRateLimitRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_coresdk_v1_CheckRateLimitRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coresdk_v1_CheckRateLimitResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_coresdk_v1_CheckRateLimitResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coresdk_v1_ResetRateLimitRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_coresdk_v1_ResetRateLimitRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coresdk_v1_ResetRateLimitResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_coresdk_v1_ResetRateLimitResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032coresdk/v1/ratelimit.proto\022\ncoresdk.v1" +
      "\032\027coresdk/v1/common.proto\"\203\001\n\025CheckRateL" +
      "imitRequest\022\020\n\003key\030\001 \001(\tR\003key\022\033\n\ttenant_" +
      "id\030\002 \001(\tR\010tenantId\022\024\n\005limit\030\003 \001(\rR\005limit" +
      "\022%\n\016window_seconds\030\004 \001(\rR\rwindowSeconds\"" +
      "\247\001\n\026CheckRateLimitResponse\022\030\n\007allowed\030\001 " +
      "\001(\010R\007allowed\022\034\n\tremaining\030\002 \001(\rR\tremaini" +
      "ng\022$\n\016retry_after_ms\030\003 \001(\004R\014retryAfterMs" +
      "\022/\n\005error\030\004 \001(\0132\031.coresdk.v1.ProblemDeta" +
      "ilR\005error\"F\n\025ResetRateLimitRequest\022\020\n\003ke" +
      "y\030\001 \001(\tR\003key\022\033\n\ttenant_id\030\002 \001(\tR\010tenantI" +
      "d\"2\n\026ResetRateLimitResponse\022\030\n\007success\030\001" +
      " \001(\010R\007success2\304\001\n\020RateLimitService\022W\n\016Ch" +
      "eckRateLimit\022!.coresdk.v1.CheckRateLimit" +
      "Request\032\".coresdk.v1.CheckRateLimitRespo" +
      "nse\022W\n\016ResetRateLimit\022!.coresdk.v1.Reset" +
      "RateLimitRequest\032\".coresdk.v1.ResetRateL" +
      "imitResponseB.Z,github.com/coresdk-dev/s" +
      "dk-go/gen/coresdk/v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          coresdk.v1.Common.getDescriptor(),
        });
    internal_static_coresdk_v1_CheckRateLimitRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_coresdk_v1_CheckRateLimitRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_coresdk_v1_CheckRateLimitRequest_descriptor,
        new java.lang.String[] { "Key", "TenantId", "Limit", "WindowSeconds", });
    internal_static_coresdk_v1_CheckRateLimitResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_coresdk_v1_CheckRateLimitResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_coresdk_v1_CheckRateLimitResponse_descriptor,
        new java.lang.String[] { "Allowed", "Remaining", "RetryAfterMs", "Error", });
    internal_static_coresdk_v1_ResetRateLimitRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_coresdk_v1_ResetRateLimitRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_coresdk_v1_ResetRateLimitRequest_descriptor,
        new java.lang.String[] { "Key", "TenantId", });
    internal_static_coresdk_v1_ResetRateLimitResponse_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_coresdk_v1_ResetRateLimitResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_coresdk_v1_ResetRateLimitResponse_descriptor,
        new java.lang.String[] { "Success", });
    descriptor.resolveAllFeaturesImmutable();
    coresdk.v1.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
